### ISSUE TITLE
Clover Json response with "/pay/key" is not Returning pem .

### ISSUE THREAD

**Issue by prasad47** [cloverhackathons/DeveloperPayAPI#1]
Hi hackthons,

We are trying to process Credit card with the Provided example .. I see the Program expecting  pem from the Json response from following url .
   url = targetEnv + merchantID + '/pay/key';
But it is returning an object with Following Properties :- 
{"modulus":"modulus","exponent":"Exponent","prefix":"prefix"} 

Leading to an Error  :- 
crypto.js:319
    var key = options.key || options;
                     ^

TypeError: Cannot read property 'key' of undefined
    at Object.publicEncrypt (crypto.js:319:22)

Can you suggest what is Missing from My Side 

Thanks,
Prasad.

**Comment by raymolee** [comment]
The pem is not included if your app does not have the process credit cards permission, which is required to use the developer pay API. 

Also if you change any permissions for your app, any merchants and test merchants that have your app already installed will have to uninstall/reinstall the app to apply the new permissions.
